export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'

export const DELETE_PRODUCTS = 'DELETE_PRODUCTS'
export const DELETE_PRODUCTS_SUCCESS = 'DELETE_PRODUCTS_SUCCESS'
export const DELETE_PRODUCTS_ERROR = 'DELETE_PRODUCTS_ERROR'

export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const START_EDIT_PRODUCT = 'START_EDIT_PRODUCT'
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR'

// Alerts
export const SHOW_ALERT = 'SHOW_ALERT'
export const COVER_ALERT = 'COVER_ALERT'